[Application]
#порт веб сервера на котором он работает
Port = "8080"

[Groups]
#дефолтный родитель для всех созданных групп если не задан при создании
default_parent = 1
#дефолтное значение лимита вывода в списке групп
limit = 4

[Tasks]
#дефолтное значение группы для вновь созданное задачи
default_group = 2
#количество символов у id тасков
tasks_length = 6

